// Shared, cached loader for /history.json — the daily on-chain snapshot bank
// (price, holders, cost basis, supply tiers, F&G). Several charts need it;
// this fetches it once per session and hands everyone the same promise.
// Resolves to [] on any failure so callers can treat "no data" uniformly.
let promise = null;

export function loadHistory() {
  if (!promise) {
    promise = fetch("/history.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : []))
      .then(d => (Array.isArray(d) ? d : []))
      .catch(() => []);
  }
  return promise;
}

// Shared, cached loader for /price-history.json — the DENSE daily price series
// (built in CI from all price sources, weekly-refreshed) the charts draw from,
// so the early history isn't the ~weekly cadence of the model-fit bundle. Same
// []-on-failure contract; the drawn line falls back to the bundle if it's absent.
let pricePromise = null;
export function loadPriceHistory() {
  if (!pricePromise) {
    pricePromise = fetch("/price-history.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : []))
      .then(d => (Array.isArray(d) ? d : []))
      .catch(() => []);
  }
  return pricePromise;
}

// Shared, cached loader for /longshort.json — the daily futures POSITIONING bank
// (Hyperliquid on-chain funding + open interest; CEX L/S is geo-blocked from CI).
// Data-gated: fills in as the daily banker accumulates. []-on-failure.
let lsPromise = null;
export function loadLongShort() {
  if (!lsPromise) {
    lsPromise = fetch("/longshort.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : []))
      .then(d => (Array.isArray(d) ? d : []))
      .catch(() => []);
  }
  return lsPromise;
}

// Shared, cached loader for /btc-mvrv.json — Bitcoin's ~decade of MVRV history
// (Coin Metrics community API, banked monthly in CI) used as the CONTEXT backdrop
// for SPX6900's short MVRV. Resolves to { points: [] } on any failure so callers
// can treat "no data yet" uniformly (the bundle is generated by the btc-mvrv workflow).
let btcMvrvPromise = null;
export function loadBtcMvrv() {
  if (!btcMvrvPromise) {
    btcMvrvPromise = fetch("/btc-mvrv.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.points) ? d : { points: [] }))
      .catch(() => ({ points: [] }));
  }
  return btcMvrvPromise;
}

// Friendly copy for live-API failures. The raw error (JSON parse noise, proxy
// statuses) is meaningless to visitors — never show it in the UI.
export const LIVE_DATA_DOWN = "Live data is temporarily unavailable — try again in a minute.";
