// Shared, cached loader for /history.json — the daily on-chain snapshot bank
// (price, holders, cost basis, supply tiers, F&G). Several charts need it;
// this fetches it once per session and hands everyone the same promise.
// Resolves to [] on any failure so callers can treat "no data" uniformly.
let promise = null;

export function loadHistory() {
  if (!promise) {
    promise = fetch("/history.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : []))
      .then(d => (Array.isArray(d) ? d : []))
      .catch(() => []);
  }
  return promise;
}

// Shared, cached loader for /price-history.json — the DENSE daily price series
// (built in CI from all price sources, weekly-refreshed) the charts draw from,
// so the early history isn't the ~weekly cadence of the model-fit bundle. Same
// []-on-failure contract; the drawn line falls back to the bundle if it's absent.
let pricePromise = null;
export function loadPriceHistory() {
  if (!pricePromise) {
    pricePromise = fetch("/price-history.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : []))
      .then(d => (Array.isArray(d) ? d : []))
      .catch(() => []);
  }
  return pricePromise;
}

// Shared, cached loader for /longshort.json — the daily futures POSITIONING bank
// (Hyperliquid on-chain funding + open interest; CEX L/S is geo-blocked from CI).
// Data-gated: fills in as the daily banker accumulates. []-on-failure.
let lsPromise = null;
export function loadLongShort() {
  if (!lsPromise) {
    lsPromise = fetch("/longshort.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : []))
      .then(d => (Array.isArray(d) ? d : []))
      .catch(() => []);
  }
  return lsPromise;
}

// Shared, cached loader for /btc-mvrv.json — Bitcoin's ~decade of MVRV history
// (Coin Metrics community API, banked monthly in CI) used as the CONTEXT backdrop
// for SPX6900's short MVRV. Resolves to { points: [] } on any failure so callers
// can treat "no data yet" uniformly (the bundle is generated by the btc-mvrv workflow).
let btcMvrvPromise = null;
let freeFloatPeersPromise = null;
// BTC + ETH free float (liquid supply %) vs days-since-inception — Coin Metrics community,
// banked by the freefloat-peers workflow. Resolves to { btc, eth } arrays (empty on any error).
export function loadFreeFloatPeers() {
  if (!freeFloatPeersPromise) {
    freeFloatPeersPromise = fetch("/freefloat-peers.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => ({ btc: d?.btc || [], eth: d?.eth || [] }))
      .catch(() => ({ btc: [], eth: [] }));
  }
  return freeFloatPeersPromise;
}

export function loadBtcMvrv() {
  if (!btcMvrvPromise) {
    btcMvrvPromise = fetch("/btc-mvrv.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.points) ? d : { points: [] }))
      .catch(() => ({ points: [] }));
  }
  return btcMvrvPromise;
}

// Shared, cached loader for /onchain.json — the SPX6900 on-chain valuation &
// distribution WEEKLY series (Supply in Profit %, concentration, gini, HODL waves),
// re-executed from Dune weekly in CI (build-onchain.mjs). Resolves to null on any
// failure so callers can fall back to the bundled src/spx-onchain.js.
let onchainPromise = null;
export function loadOnchain() {
  if (!onchainPromise) {
    onchainPromise = fetch("/onchain.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (Array.isArray(d) && d.length ? d : null))
      .catch(() => null);
  }
  return onchainPromise;
}

// Shared, cached loader for /aeon-onchain.json — the Project Aeon NFT holder
// reconstruction (owners, holder-age/HODL waves, concentration, flow), an OBJECT
// { updated, supply, current, series }. Null on failure → bundled AEON_ONCHAIN.
let aeonPromise = null;
export function loadAeon() {
  if (!aeonPromise) {
    aeonPromise = fetch("/aeon-onchain.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.series) && d.series.length ? d : null))
      .catch(() => null);
  }
  return aeonPromise;
}

// Shared, cached loader for /aeon-sales.json — the Aeon marketplace floor/volume series
// (daily floor ETH+USD, volume, per-sale scatter). Null on failure → bundled AEON_SALES.
let aeonSalesPromise = null;
export function loadAeonSales() {
  if (!aeonSalesPromise) {
    aeonSalesPromise = fetch("/aeon-sales.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.daily) && d.daily.length ? d : null))
      .catch(() => null);
  }
  return aeonSalesPromise;
}

// Shared, cached loader for /aeon-rarity.json — the Project Aeon trait-rarity data
// (per-token rank/score/traits + trait-frequency tables). ~1.35MB → fetch-only (not
// bundled); the rarity chart is lazy-loaded so it never touches the base bundle.
let aeonRarityPromise = null;
export function loadAeonRarity() {
  if (!aeonRarityPromise) {
    aeonRarityPromise = fetch("/aeon-rarity.json", { cache: "force-cache" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.tokens) && d.tokens.length ? d : null))
      .catch(() => null);
  }
  return aeonRarityPromise;
}

// Shared, cached loader for /aeon-listings.json — active OpenSea listings joined to
// rarity (the deal-finder feed). Null on failure so the chart shows an empty state.
let aeonListPromise = null;
export function loadAeonListings() {
  if (!aeonListPromise) {
    aeonListPromise = fetch("/aeon-listings.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.listings) && d.listings.length ? d : null))
      .catch(() => null);
  }
  return aeonListPromise;
}

// Aeon market valuation (MVRV / supply-in-profit / URPD / deals / biggest sales / trait premiums).
let aeonMktPromise = null;
export function loadAeonMarket() {
  if (!aeonMktPromise) aeonMktPromise = fetch("/aeon-market.json", { cache: "no-store" }).then(r => r.ok ? r.json() : null).then(d => d && d.valuation ? d : null).catch(() => null);
  return aeonMktPromise;
}
// Aeon trader intelligence (wallet P&L leaderboard).
let aeonTradersPromise = null;
export function loadAeonTraders() {
  if (!aeonTradersPromise) aeonTradersPromise = fetch("/aeon-traders.json", { cache: "no-store" }).then(r => r.ok ? r.json() : null).then(d => d && Array.isArray(d.top) ? d : null).catch(() => null);
  return aeonTradersPromise;
}

// Shared, cached loader for /urpd.json — the cost-basis distribution snapshot (URPD)
// from the local FIFO engine. Resolves to null on failure so the caller falls back to
// the bundled src/spx-urpd.js.
let urpdPromise = null;
export function loadUrpd() {
  if (!urpdPromise) {
    urpdPromise = fetch("/urpd.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.buckets) && d.buckets.length ? d : null))
      .catch(() => null);
  }
  return urpdPromise;
}

// Shared, cached loader for /whales.json — the biggest CURRENT holders with how much each has
// added or shed over the lookback windows (from the FIFO engine; CEX/LP/bridge already excluded,
// so these are real holders). Resolves to null on failure — the whale watcher then data-gates.
let whalesPromise = null;
export function loadWhales() {
  if (!whalesPromise) {
    whalesPromise = fetch("/whales.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.wallets) && d.wallets.length ? d : null))
      .catch(() => null);
  }
  return whalesPromise;
}

// Shared, cached loader for /cex-flow.json — daily CEX/LP/custody balances + flow (Dune baseline
// + daily snapshot-forward). Resolves to null on failure so callers fall back to src/cex-flow.js.
let cexFlowPromise = null;
export function loadCexFlow() {
  if (!cexFlowPromise) {
    cexFlowPromise = fetch("/cex-flow.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.days) && d.days.length ? d : null))
      .catch(() => null);
  }
  return cexFlowPromise;
}

// Shared, cached loader for /chain-wallets.json — multi-chain weekly wallet counts
// (ETH+Base+Solana), refreshed by chain-wallets.yml. Resolves to null on any failure so
// callers fall back to the bundled src/chain-wallets.js.
let chainWalletsPromise = null;
export function loadChainWallets() {
  if (!chainWalletsPromise) {
    chainWalletsPromise = fetch("/chain-wallets.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (Array.isArray(d) && d.length ? d : null))
      .catch(() => null);
  }
  return chainWalletsPromise;
}

// Shared, cached loader for /valuation.json — the weighted valuation composite
// (over/under-valued oscillator + today's weighted lens breakdown), regenerated
// daily by the snapshot cron. Resolves to null on any failure so the chart can
// show a graceful "being computed" state.
let valuationPromise = null;
export function loadValuation() {
  if (!valuationPromise) {
    valuationPromise = fetch("/valuation.json", { cache: "no-store" })
      .then(r => (r.ok ? r.json() : null))
      .then(d => (d && Array.isArray(d.series) && d.series.length ? d : null))
      .catch(() => null);
  }
  return valuationPromise;
}

// Friendly copy for live-API failures. The raw error (JSON parse noise, proxy
// statuses) is meaningless to visitors — never show it in the UI.
export const LIVE_DATA_DOWN = "Live data is temporarily unavailable — try again in a minute.";
